const Menu = [
  {
    id: 1,
    pname: "Smart Mobile",
    category: "mobile",
    price: 32000,
    pimage: "images/m1.jpg",
  },
  {
    id: 2,
    pname: "Smart Mobile",
    category: "mobile",
    price: 28000,
    pimage: "images/m2.jpg",
  },
  {
    id: 3,
    pname: "Smart Mobile",
    category: "mobile",
    price: 31000,
    pimage: "images/m3.jpg",
  },
  {
    id: 4,
    pname: "Smart Mobile",
    category: "mobile",
    price: 12000,
    pimage: "images/m4.jpg",
  },
  {
    id: 5,
    pname: "shirt",
    category: "shirt",
    price: 1100,
    pimage: "images/s1.jpg",
  },
  {
    id: 6,
    pname: "shirt",
    category: "shirt",
    price: 900,
    pimage: "images/s2.jpg",
  },
  {
    id: 7,
    pname: "shirt",
    category: "shirt",
    price: 1500,
    pimage: "images/s3.jpg",
  },
  {
    id: 8,
    pname: "shirt",
    category: "shirt",
    price: 1700,
    pimage: "images/s4.jpg",
  },
  {
    id: 9,
    pname: "Smart Watch",
    category: "watch",
    price: 5600,
    pimage: "images/w1.jpg",
  },
  {
    id: 10,
    pname: "Smart Watch",
    category: "watch",
    price: 5100,
    pimage: "images/w2.jpg",
  },
  {
    id: 11,
    pname: "Smart Watch",
    category: "watch",
    price: 4600,
    pimage: "images/w3.jpg",
  },
  {
    id: 12,
    pname: "Smart Watch",
    category: "watch",
    price: 3600,
    pimage: "images/w4.jpg",
  },
  {
    id: 13,
    pname: "Smart Watch",
    category: "watch",
    price: 2000,
    pimage: "images/w5.jpg",
  },
];
export default Menu;
